image: 'maven:3-jdk-8'
stages:
  - test
  - build
services:
  - 'mysql:latest'
variables:
  MYSQL_DATABASE: movieDb
  MYSQL_CI_URL: jdbc:mysql://mysql/movieDb
  MYSQL_USER: poc
  MYSQL_PASSWORD: poc
  MYSQL_ROOT_PASSWORD: root
cache:
  paths:
  - .m2/repository
  - target
maven-test:
  image: maven:3-jdk-8
  stage: test
  script: "mvn test -B"
maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn package -U"
  artifacts:
    paths:
      - target/*.jar

